### PR TITLE
fix key not exist in json when encode

### PR DESCRIPTION
**Pull request by erlangzhang**

### CODE REVIEW

**Comment by JARMourato** [comment]
Hey @erlangzhang thank you for your PR. Just for the sake of documentation, can you state how you came to this problem ? and also add a test to cover this case ?

**Comment by JARMourato** [comment]
@erlangzhang any update ?

**Comment by erlangzhang** [comment]
> @erlangzhang any update ?

hey,  sorry, this code is to fix key not exist in json when decode. such as

`class Animal: Kodable {
    public var name: String? = "bird"
    public var family: String? = "ff"
    required init() {}
}

some.json
{
     "family": "aaaa"
}`

the key `name` in Animal will be set to nil in your code, so i add contain function to check if key exist in json

**Comment by erlangzhang** [comment]
this project is very good and useful

**Comment by rogerluan** [comment]
Hey @erlangzhang 👋 

Correct me if I'm wrong (@JARMourato also), but this design wouldn't match Apple's `Decodable` decoding design - they also replace the value. What you can do, though, is use Kodable's `defaultValue` to your fallback:

```swift
struct User: Kodable {
    @Coding(default: "bird") var name: String?
    @Coding(default: "ff") var family: String?
}
```

That would result in the experience you're expecting.

Hope this works out for you

**Comment by erlangzhang** [comment]
> Hey @erlangzhang 👋
> 
> Correct me if I'm wrong (@JARMourato also), but this design wouldn't match Apple's `Decodable` decoding design - they also replace the value. What you can do, though, is use Kodable's `defaultValue` to your fallback:
> 
> ```swift
> struct User: Kodable {
>     @Coding(default: "bird") var name: String?
>     @Coding(default: "ff") var family: String?
> }
> ```
> 
> That would result in the experience you're expecting.
> 
> Hope this works out for you

yes, but sometimes i think just use public var name: String? = "bird" is more simple, if use my code. because may be a lot of properties may not need to add @Coding

**Comment by erlangzhang** [comment]
some times, the json return by server may not missing key after the app published. people may not add @Coding to the property, this will make mistake.

**Comment by JARMourato** [comment]
Hey @erlangzhang @rogerluan thank you both for your comments. I've given some thought into this. 

@erlangzhang Your point is definitely valid here https://github.com/JARMourato/Kodable/pull/5#issuecomment-876093224 

it will be overridden by `nil` since there is no value for that key in the JSON. But that is just the default behaviour of `Codable`. By design, I want to keep `Kodable` as close to the default behaviour as it can be. In case we want to customise the behaviour, then we use `Coding`.

In light of this, I believe this PR would change that and would make `Kodable` have unpredictable behaviour. Hence, since it it goes against the intended design, regrettably, I'll be closing this one @erlangzhang

**Comment by JARMourato** [comment]
I'll give it a day and then I'll close it.

**Comment by rogerluan** [comment]
I agree @JARMourato 👍

**Comment by JARMourato** [comment]
I guess I gave it 1 + 20 😅

**Pull request closed without merging**
